# Evaluation config
BROKER_NAME: HiveMQ CE
ENV_FILE: env/hivemq_ce.env
NR_OF_MESSAGES: 100
NR_OF_EXPERIMENTS: 10
CLIENT_COMPOSE_FILE: docker-compose.yml
DOCKER_NETWORK: evaluationnet

# MQTT config
BROKER_URL: HiveMQBroker
BROKER_PORT: 1883
TOPIC: broker/evaluation/topic
QOS: 2
MAXIMUM_MESSAGE_INTERVAL: 300
TLS_ENABLED: False
PUBLISH_INTERVAL: 1
REATTEMPTS: -1
REATTEMPT_MAX_DELAY: 60

# Reliability config
BROKER_CONTAINER: HiveMQBroker
BROKER_COMPOSE_FILE: brokers/HiveMQ/docker-compose-HiveMQ.yml
NR_OF_FAILURES: 2
FAILURE_INTERVAL: 60
FAILURE_PERIOD: 180
# MAXIMUM_CLIENT_DISCONNECTS: 2
# CLIENT_DISCONNECT_INTERVAL: 2
# CLIENT_DISCONNECT_PERIOD: 300



