BROKER_URL: HiveMQBroker
BROKER_PORT: 1883
TOPIC: broker/evaluation/topic
QOS: 2
TLS_ENABLED: False
NR_OF_MESSAGES: 100
REATTEMPTS: -1
REATTEMPT_MAX_DELAY: 60
MAXIMUM_MESSAGE_INTERVAL: 30
# MAXIMUM_CLIENT_DISCONNECTS: 2
# CLIENT_DISCONNECT_INTERVAL: 2
# CLIENT_DISCONNECT_PERIOD: 300

