# Evaluation config
BROKER_NAME: Mosquitto
ENV_FILE: env/mosquitto.env
NR_OF_MESSAGES: 100
NR_OF_EXPERIMENTS: 10
CLIENT_COMPOSE_FILE: docker-compose.yml
DOCKER_NETWORK: evaluationnet

# MQTT config
BROKER_URL: MosquittoBroker
BROKER_PORT: 1883
TOPIC: broker/evaluation/topic
QOS: 2
MAXIMUM_MESSAGE_INTERVAL: 300
TLS_ENABLED: False
PUBLISH_INTERVAL: 1
REATTEMPTS: -1
REATTEMPT_MAX_DELAY: 60

# Reliability config
BROKER_CONTAINER: MosquittoBroker
BROKER_COMPOSE_FILE: brokers/Mosquitto/docker-compose-Mosquitto.yml
NR_OF_FAILURES: 2
FAILURE_INTERVAL: 60
FAILURE_PERIOD: 180
#MAXIMUM_CLIENT_DISCONNECTS: 2
#CLIENT_DISCONNECT_INTERVAL: 2
#CLIENT_DISCONNECT_PERIOD: 300

